# Generated by Django 3.2.2 on 2021-05-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_auto_20210507_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumcategory',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='musiclist',
            old_name='category',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='musiclist',
            name='upload_music',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
