# Generated by Django 3.2.2 on 2021-05-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_alter_musiclist_upload_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_music', models.FileField(upload_to='FavoriteMusic')),
            ],
        ),
        migrations.CreateModel(
            name='NewMp3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_music', models.FileField(upload_to='NewMp3')),
            ],
        ),
        migrations.CreateModel(
            name='PopularMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_music', models.FileField(upload_to='PopularMusic')),
            ],
        ),
        migrations.AlterField(
            model_name='musiclist',
            name='upload_music',
            field=models.FileField(upload_to=''),
        ),
    ]
