# Generated by Django 3.2.2 on 2021-05-08 23:46

from django.db import migrations, models
import music_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_auto_20210508_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='upload_music',
            field=models.FileField(upload_to=music_app.models.AlbumCategory),
        ),
    ]
