# Generated by Django 3.2.2 on 2021-05-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0007_alter_musiclist_upload_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musiclist',
            old_name='name',
            new_name='music_name',
        ),
        migrations.AddField(
            model_name='musiclist',
            name='artist_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
