# Generated by Django 3.2.2 on 2021-05-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0009_musiclist_artist_alphabet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='upload_music',
            field=models.FileField(upload_to="<class 'music_app.models.AlbumCategory'>"),
        ),
    ]
