# Generated by Django 3.2.2 on 2021-05-09 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0010_alter_musiclist_upload_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='upload_music',
            field=models.FileField(upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.albumcategory')),
        ),
    ]
