# Generated by Django 3.2.2 on 2021-05-09 00:40

from django.db import migrations, models
import music_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0014_alter_musiclist_upload_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='upload_music',
            field=models.FileField(upload_to=music_app.models.upload_location),
        ),
    ]
