# Generated by Django 3.2.2 on 2021-05-12 04:15

from django.db import migrations, models
import music_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0019_alter_albummusic_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummusic',
            name='upload_thumbnail',
            field=models.ImageField(null=True, upload_to=music_app.models.AlbumMusic.file_location),
        ),
    ]
