# Generated by Django 3.2.2 on 2021-05-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0020_albummusic_upload_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_app.albumcategory'),
        ),
    ]
