# Generated by Django 3.2.2 on 2021-05-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0023_alter_musiclist_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummusic',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_list', to='music_app.albumcategory'),
        ),
    ]
