# Generated by Django 3.2.2 on 2021-05-12 18:22

from django.db import migrations, models
import music_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0025_alter_albummusic_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummusic',
            name='upload_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=music_app.models.AlbumMusic.file_location),
        ),
    ]
