# Generated by Django 3.2.2 on 2021-05-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0026_alter_albummusic_upload_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummusic',
            name='numdownload',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
